# Generated by Django 5.2.7 on 2025-10-31 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='module',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='module',
            name='description',
        ),
        migrations.RemoveField(
            model_name='module',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='module',
            name='resource_file',
        ),
        migrations.RemoveField(
            model_name='module',
            name='title',
        ),
        migrations.RemoveField(
            model_name='module',
            name='video_url',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='category',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='file',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='module',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='title',
        ),
        migrations.RemoveField(
            model_name='workbook',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='workbook',
            name='description',
        ),
        migrations.RemoveField(
            model_name='workbook',
            name='pdf_file',
        ),
        migrations.RemoveField(
            model_name='workbook',
            name='price',
        ),
        migrations.RemoveField(
            model_name='workbook',
            name='title',
        ),
        migrations.RemoveField(
            model_name='workbookpurchase',
            name='date',
        ),
        migrations.RemoveField(
            model_name='workbookpurchase',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='workbookpurchase',
            name='purchaser_content_type',
        ),
        migrations.RemoveField(
            model_name='workbookpurchase',
            name='purchaser_object_id',
        ),
        migrations.RemoveField(
            model_name='workbookpurchase',
            name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='workbookpurchase',
            name='workbook',
        ),
    ]
