# Generated by Django 5.2.7 on 2025-11-03 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
        ('projects', '0003_delete_module_delete_resource_delete_workbook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='skills_required',
            field=models.ManyToManyField(blank=True, related_name='projects', to='achievements.skill'),
        ),
    ]
