# Generated by Django 5.2.7 on 2025-10-31 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_module_created_at_remove_module_created_by_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Module',
        ),
        migrations.DeleteModel(
            name='Resource',
        ),
        migrations.DeleteModel(
            name='Workbook',
        ),
        migrations.DeleteModel(
            name='WorkbookPurchase',
        ),
    ]
