# Generated by Django 5.2.7 on 2025-10-31 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='issued_by',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='issued_to',
        ),
        migrations.DeleteModel(
            name='Badge',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.DeleteModel(
            name='Certificate',
        ),
    ]
