# Generated by Django 5.2.7 on 2025-11-03 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corporatepartnerprofile',
            options={'permissions': [('manage_corporate_projects', 'Can manage corporate projects'), ('view_corporate_analytics', 'Can view corporate analytics')]},
        ),
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'permissions': [('view_student_profile', 'Can view student profile'), ('edit_student_profile', 'Can edit student profile')]},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('view_own_profile', 'Can view own profile'), ('edit_own_profile', 'Can edit own profile'), ('manage_students', 'Can manage students'), ('manage_projects', 'Can manage projects')]},
        ),
    ]
