# Generated by Django 5.2.7 on 2025-11-03 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_corporatepartnerprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corporatepartnerprofile',
            options={},
        ),
        migrations.AlterModelOptions(
            name='studentprofile',
            options={},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
