# Generated by Django 5.2.7 on 2025-11-03 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
        ('projects', '0004_alter_project_skills_required'),
        ('users', '0003_alter_corporatepartnerprofile_options_and_more'),
    ]

    operations = [
        # First, delete the ManyToMany relationships
        migrations.RemoveField(
            model_name='studentprofile',
            name='badges',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='certificates',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='skills',
        ),
        # Delete the models
        migrations.DeleteModel(
            name='Badge',
        ),
        migrations.DeleteModel(
            name='Certificate',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        # Re-add the ManyToMany fields pointing to achievements
        migrations.AddField(
            model_name='studentprofile',
            name='badges',
            field=models.ManyToManyField(blank=True, related_name='students', to='achievements.badge'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='certificates',
            field=models.ManyToManyField(blank=True, related_name='students', to='achievements.certificate'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='students', to='achievements.skill'),
        ),
    ]
